[window]
width = 1920
height = 1080
vsync = true

[fs_protocol]
asset = "assets"
font = "assets/fonts"
model = "assets/models"
shader = "assets/shaders"
shader_glsl = "assets/shaders/glsl"
shader_slang = "assets/shaders/slang"
# shader_cache = "assets/cache/shaders"
shader_cache = "cache/shaders"
texture = "assets/textures"

[thread]
num_override = 0

[debug]
log_level = 1
log_time = false
log_color = true
log_line_info = true
backtrace = true
