set(CMAKE_C_FLAGS "")
set(CMAKE_CXX_FLAGS "")

set(COMMON_FLAGS "-Wall -Wno-sign-compare")

set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS} -O0 -g -ggdb -DAPH_DEBUG ${COMMON_FLAGS}")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -O3 ${COMMON_FLAGS}")

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED required)
